name: ztv
description: IPTV
publish_to: 'none'
version: 2.1.7+32

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  http: ^0.13.3
  video_player: ^2.4.6
  file_picker: ^4.5.1
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  path: ^1.8.0
  flutter_vlc_player: ^7.1.5
  in_app_purchase: ^3.0.6
  cloud_firestore: ^3.2.1
  google_sign_in: ^5.3.3
  shared_preferences: ^2.0.6
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path: "icon/ztv.jpg"
  android: true
  ios: true
  image_path_ios: "icon/ztv.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/local.properties
    - icon/ztv.jpg
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
