name: ztv
description: IPTV
publish_to: 'none'
version: 3.0.1+43

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  http: ^0.13.5
  video_player: ^2.4.10
  file_picker: ^5.2.3
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0+3
  path: ^1.8.0
  flutter_vlc_player: ^7.1.5
  in_app_purchase: ^3.1.1
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0
  shared_preferences: ^2.0.6
  flutter_signin_button: ^2.0.0
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path: "icon/ztv.jpg"
  android: true
  ios: true
  image_path_ios: "icon/ztv.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/local.properties
    - assets/icon/ztv.jpg
    - assets/icon/google.png
  generate: true

  uses-material-design: true
